### ISSUE TITLE
notes .h 

### ISSUE THREAD

**Issue by rafaelcorsi** [wesleygas/academico-embarcados#1]
https://github.com/wesleygas/academico-embarcados/blob/c9e634e2a4b79dd02da8cd35a41a56bd9561cfb8/APS1-%20Musicas/src/main.c#L55

tudo isso poderia ter ido para um .h e você daria include depois! no main.c

**Comment by rafaelcorsi** [comment]
poderiam colocar tudo no note.h ou criar um .h por música !

**Comment by wesleygas** [comment]
Músicas movidas para songs.h

**Comment by rafaelcorsi** [comment]
Poderia criar um outro pinos.h e jogar todos os #defines de pino!
