### ISSUE TITLE
repeteco = função

### ISSUE THREAD

**Issue by rafaelcorsi** [wesleygas/academico-embarcados#2]
https://github.com/wesleygas/academico-embarcados/blob/c9e634e2a4b79dd02da8cd35a41a56bd9561cfb8/APS1-%20Musicas/src/main.c#L295

trechos de código similar devem virar função para:
 1. reaproveitamento de código
 2. deixar o código mais fácil de entender!

**Comment by wesleygas** [comment]
Função criada

`int mus_selector(void)`
