### ISSUE TITLE
variável global = perigo!!

### ISSUE THREAD

**Issue by rafaelcorsi** [wesleygas/academico-embarcados#3]
https://github.com/wesleygas/academico-embarcados/blob/c9e634e2a4b79dd02da8cd35a41a56bd9561cfb8/APS1-%20Musicas/src/main.c#L176

só usar variável global quando REALMENTE necessário! essas duas variáveis poderiam estar no `main()`

**Comment by rafaelcorsi** [comment]
leia para entender! https://betterembsw.blogspot.com/2014/06/minimize-use-of-global-variables.html

**Comment by wesleygas** [comment]
Variáveis globais malévolas foram contidas com sucesso.
